apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Key
metadata:
  name: topic10-kmskey 
spec:
  forProvider:
    region: eu-west-3
    description: topic10-kmskey 
    pendingWindowInDays: 7
    policy: |-
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "Enable IAM User Permissions",
            "Effect": "Allow",
            "Principal": {
              "AWS": [
               "arn:aws:iam::654654303557:user/handson-topic10-produit-user",
               "arn:aws:iam::654654303557:root"
              ]
            },
            "Action": "kms:*",
            "Resource": "*"
          }
        ]
      }
    tags:
     - tagKey: asdas
       tagValue: k1
  providerConfigRef:
    name: default
