apiVersion: cloudwatchlogs.aws.crossplane.io/v1alpha1
kind: LogGroup
metadata:
  name: topic10-loggroup
spec:
  forProvider:
    logGroupName: topic10-loggroup
    region: eu-west-3
    retentionInDays: 1
    tags:
      environment: production
      project: myapp
  providerConfigRef:
    name: default
