apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: my-public-website-bucket
spec:
  providerConfigRef:
    name: default
  forProvider:
    locationConstraint: eu-west-3
    websiteConfiguration:
      indexDocument: 
        suffix: index.html
    publicAccessBlockConfiguration:
      blockPublicAcls: false
      blockPublicPolicy: false
      ignorePublicAcls: false
      restrictPublicBuckets: false
    versioningConfiguration:
      status: Suspended
    tagging:
      tagSet:
       - key: yuanchao-handson-tag
         value: handson-topic10
       - key: Project
         value: Crossplane
    policy: 
      version: 2012-10-17
      statements:
        - effect: Allow
          principal:
            allowAnon: true
          action: 
           - 's3:GetObject'
          resource: 
           - "arn:aws:s3:::my-public-website-bucket/*"